Diamonds.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Diamonds.Web.Models;
using IO.Swagger.Api;
using System.Collections.Generic;
using System.Linq;

namespace Diamonds.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ItemApi _service;

        public HomeController(ItemApi service)
        {
            _service = service;
        }

        public IActionResult Index(string message = null)
        {
            var items = _service.ApiItemGet();
            IList<ItemModel> models = items.Select(i => new ItemModel(i)).ToList();
            bool withMessage = false;
            if (!string.IsNullOrEmpty(message))
            {
                withMessage = true;
                ViewBag.Message = message;
            }
            ViewBag.WithMessage = withMessage;
            return View(models);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Diamonds.Web/Controllers/ItemsController.cs
using Diamonds.Web.Models;
using IO.Swagger.Api;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.IO;
using System.Linq;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Diamonds.Web.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ItemApi _service;
        private readonly IHostingEnvironment _host;

        public ItemsController(ItemApi service, IHostingEnvironment host)
        {
            _service = service;
            _host = host;
        }

        public IActionResult EditItem(int itemId)
        {
            ItemModel item = new ItemModel(_service.ApiItemIdGet(itemId));
            string[] metals, shapes;
            bool hasPhotos = false;
            if (item.Photos.Keys.Count > 0)
            {
                metals = item.Photos.Keys.Select(s => s.Split(';')[0]).Distinct().ToArray();
                shapes = item.Photos.Keys.Select(s => s.Split(';')[1]).Distinct().ToArray();
                ViewBag.ColumnWidth = 12 / (metals.Count() + 1);
                hasPhotos = true;
                ViewBag.Metals = metals;
                ViewBag.Shapes = shapes;
            }
            ViewBag.HasPhotos = hasPhotos;
            return View(item);
        }

        [HttpPost]
        public IActionResult UploadFile(int itemId, string material, string shape, IFormFile file)
        {
            bool updated = _service.ApiItemPost(itemId, material, shape, file.FileName, "", 0, "PHOTO").Value;

            if (updated && file.Length > 0)
            {
                using (var ms = new MemoryStream())
                {
                    string ImagesPath = Path.Combine(_host.WebRootPath, "images\\ring", file.FileName);
                    file.CopyTo(ms);
                    var fileBytes = ms.ToArray();
                    try
                    {
                        System.IO.File.WriteAllBytes(ImagesPath, fileBytes);
                        //Add notification Upload succeeded
                    }
                    catch
                    {
                        //Add Notification upload failed
                        return RedirectToAction("Index", "Home", new { message = "Error Uploading photo" });
                    }
                }
            }
            return RedirectToAction("Index", "Home", new { message = "Photo Upload Successfully"});
        }
    }
}

Diamonds.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Diamonds.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Diamonds.Web/Views/Home/Index.cshtml
@model IEnumerable<ItemModel>

@{
    ViewData["Title"] = "Product's Photos Management";
}

<script src="~/js/ItemsHandler.js"></script>

<div id="container-body" class="container">
    <h2>Photos Management</h2>

    @if (ViewBag.WithMessage)
    {
        <div class="alert-info">
            <p>@ViewBag.Message</p>
        </div>
    }

    @foreach (ItemModel item in Model)
    {
        <div class="container">
            <a href="@Url.Action("EditItem", "Items", new { itemId = item.IdITem})" class="btn btn-primary">@item.Name</a>
            @foreach(var entry in item.Photos)
            {
                <p>Item with @entry.Key has @entry.Value.Count photos</p>
            }
        </div>
    }


</div>

<script>
    var itemsUrl = "@Url.Action("GetItems", "Items")";
    var editItemUrl = "@Url.Action("EditItem", "Items")";
</script>